package topology.description.actual;

import topology.dataStructure.Connection;

//This is the connection definition in the top level description file.
public class ActualConnection extends Connection{
	
	public ActualConnectionPoint source;
	public ActualConnectionPoint target;
	
	/**
	 * This field determines whether this connection is 
	 * design for logic design purpose. When this connection is transferred from 
	 * the abstract description, this field must be 'true'. 
	 * When this connection is generated by the subnet, this field must be 'false'.
	 * If it is 'null', it means 'true' by default. 
	 */
	public String logic;

}
